sys:
  user: "leo" # ansible、k8s使用用户，需要具备sudo权限，hosts文件中也有该配置，两者需一致
  app_dir: "/home/leo/k8s-installer" # 程序执行目录
  work_dir: "/opt/ansible/tmp"
  data_dir: "/data" # docker和kubernetes使用的数据目录，系统挂载的数据盘

k8s:
  ha_mode: 1 # 是否搭建集群master高可用模式，1为是，0为否，与hosts文件中kube_master_group设置要一致
  vip: "172.16.16.16" # 分配给集群master使用的负载均衡器IP，如果是单master则为master ip
  api_port: 6443 # 请勿修改
  vip_domain: "vip.kubernetes.local" # 集群内部使用域名请勿修改
  # 负载均衡设置：master使用的负载均衡负载到所有master节点的6443端口，监听6443端口
  # 健康检查策略为超时3s、间隔5s、重试2次，算法为轮询
  service_subnet: "10.10.0.0/16"
  pod_subnet: "10.11.0.0/16"
  bip: "100.100.100.1/16" # docker bip
  hub: "hub.leocd.com" # 本地镜像仓库地址，通过hosts绑定至ansible执行机s

network:
  domain: "leocd.com" # 用于集群外访问grafana、prometheus、kibana使用，根据实际情况修改
  interface_app_cali: "ens*,eth*"
  calico_mtu: "1480"