---
- name: 准备provisioner yaml
  template:
    src:  provisioner.yaml.j2
    dest: "{{ sys.work_dir }}/provisioner.yaml"

- name: 安装provisioner
  shell: |
    cd {{ sys.work_dir }}
    kubectl apply -f provisioner.yaml --kubeconfig=/home/{{ sys.user }}//.kube/config

- name: 准备storageclass yaml
  copy:
    src: sc.yaml
    dest: "{{ sys.work_dir }}/"

- name: 设置storageclass
  shell: |
    cd {{ sys.work_dir }}
    kubectl apply -f sc.yaml --kubeconfig=/home/{{ sys.user }}//.kube/configs
