---
- name: 准备provisioner yaml
  template:
    src:  provisioner.yaml.j2
    dest: "{{ sys.work_dir }}/provisioner.yaml"

- name: 安装provisioner
  shell: |
    kubectl apply -f {{ sys.work_dir }}/provisioner.yaml --kubeconfig=/home/{{ sys.user }}/.kube/config

- name: 准备storageclass yaml
  copy:
    src: sc.yaml
    dest: "{{ sys.work_dir }}/"

- name: 设置storageclass
  shell: |
    kubectl apply -f {{ sys.work_dir }}/sc.yaml --kubeconfig=/home/{{ sys.user }}/.kube/configs
