---
- name: 6.1 获取token
  when: inventory_hostname in groups['master']
  shell: |
    source /etc/profile
    kubeadm token list | grep authentication | awk -F" " '{print $1}' | tail -n 1
  register: kubeadm_token

- name: 6.2 获取hash
  when: inventory_hostname in groups['master']
  shell: |
    openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin \
    -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: kubeadm_hash

- name: 6.3 获取certkey
  when: inventory_hostname in groups['master']
  shell: |
    source /etc/profile
    kubeadm init phase upload-certs --upload-certs | tail -n 1
  register: kubeadm_ckey

- name: 6.4 将上述结果注册为变量
  set_fact:
    kubeadm_token: "{{ hostvars[groups['master'][0]].kubeadm_token.stdout }}"
    kubeadm_hash: "{{ hostvars[groups['master'][0]].kubeadm_hash.stdout }}"
    kubeadm_ckey: "{{ hostvars[groups['master'][0]].kubeadm_ckey.stdout }}"

- name: 6.5 其余Master节点加入集群
  when: k8s.ha_mode|int == 1 and inventory_hostname in groups['kube_master_group']
  shell: |
    kubeadm join {{ k8s.vip_domain }}:{{ k8s.api_port }} --token {{ kubeadm_token }} \
    --discovery-token-ca-cert-hash sha256:{{ kubeadm_hash }} \
    --control-plane --certificate-key {{ kubeadm_ckey }}
    sleep 300

- name: 6.6 work节点加入集群
  when: inventory_hostname in groups['kube_worker']
  shell: |
    kubeadm join {{ k8s.vip_domain }}:{{ k8s.api_port }} --token {{ kubeadm_token }} \
    --discovery-token-ca-cert-hash sha256:{{ kubeadm_hash }}
    sleep 300

- name: 6.7 准备metrics-server yaml
  when: inventory_hostname in groups['master']
  template:
    src: metrics-server.yaml.j2
    dest: "{{ sys.work_dir }}/metrics-server.yaml"

- name: 6.8 安装metrics-server
  when: inventory_hostname in groups['master']
  shell: |
    kubectl apply -f {{ sys.work_dir }}/metrics-server.yaml --kubeconfig=/home/{{ sys.user }}/.kube/config

- name: 6.9 准备coredns yaml
  when: inventory_hostname in groups['master']
  template:
    src: coredns.yaml.j2
    dest: "{{ sys.work_dir }}/coredns.yaml"

- name: 6.10 安装coredns
  when: inventory_hostname in groups['master']
  shell: |
    kubectl apply -f {{ sys.work_dir }}/coredns.yaml --kubeconfig=/home/{{ sys.user }}/.kube/config

- name: 6.11 准备Calico yaml
  when: inventory_hostname in groups['master']
  template:
    src: "calico.yaml.j2"
    dest: "{{ sys.work_dir }}/calico.yaml"

- name: 6.12 安装Calico
  when: inventory_hostname in groups['master']
  shell: |
    kubectl apply -f {{ sys.work_dir }}/calico.yaml --kubeconfig=/home/{{ sys.user }}/.kube/config

- name: 6.13 准备nginx ingress yaml
  when: inventory_hostname in groups['master']
  template:
    src: nginx-ingress.yaml.j2
    dest: "{{ sys.work_dir }}/nginx-ingress.yaml"

- name: 6.14 安装nginx ingress
  when: inventory_hostname in groups['master']
  shell: |
    kubectl apply -f {{ sys.work_dir }}/nginx-ingress.yaml --kubeconfig=/home/{{ sys.user }}/.kube/config
