---
- name: 加载镜像包
  shell: |
    docker load -i k8s.tar.gz
    docker images | grep -v -w IMAGE | sed 's#harbor.kubernetes.lo#{{ k8s.hub }}:5000#g' | awk '{print "docker tag"" " $3" "$1":"$2}'|sh
    docker images | grep -v -w IMAGE | grep harbor.kubernetes.lo | awk '{print "docker rmi"" "$1":"$2}'|sh
    docker images | grep {{ k8s.hub }} | awk '{print "docker push"" "$1":"$2}'|sh
  args:
    chdir: "{{ sys.app_dir }}/package"

- name: 4.1 生成kubeadm配置文件
  template:
    dest: "{{ sys.work_dir }}/kubeadm-config.yaml"
    src: kubeadm-config.yaml.j2

- name: 4.2 初始化集群第一个节点
  shell: |
    mkdir -p /home/{{ sys.user }}/.kube
    kubeadm init --config={{ sys.work_dir }}/kubeadm-config.yaml --upload-certs
    cp -i /etc/kubernetes/admin.conf /home/{{ sys.user }}/.kube/config
    chown -R {{ sys.user }}:{{ sys.user }} /home/{{ sys.user }}/.kube

- name: 4.3 修改yaml文件存储位置权限
  shell: |
    chown -R {{ sys.user }}:{{ sys.user }} {{ sys.work_dir }}